### ISSUE TITLE
403 heartbeat within Firefox

### ISSUE THREAD

**Issue by wadethestealth** [wakatime/chrome-wakatime#84] opened 2019-11-14 15:53 UTC
After cloning and installing into a temporary firefox environment using web-ext run.
The plugin loads correctly but upon sending a heart beat, it gets a 403 response

sample request:
`{"entity":"about:preferences//undefined","type":"domain","time":"1573746245","project":"<<LAST_PROJECT>>","is_debugging":false,"plugin":"browser-wakatime/1.0.2"}`

response:
403 (Forbidden)
`{"error":"Missing start date."}`

Cookies are cleared and login is correctly registered by wakatime.

cc: @Eeems

**Comment by Eeems** [comment] 2019-11-14 15:56
I can confirm that this is also happening for me.

@alanhamlett has the API been changed?

**Comment by wadethestealth** [comment] 2019-11-14 16:01
@Eeems I located the api docs (https://wakatime.com/developers#heartbeats), but I see start as only a property of the get request not the post request. Is it possible the above request being logged is not the cause of the error but rather an attempted get request?

**Comment by gandarez** [comment] 2020-01-26 15:36
@alanhamlett any idea why is it happening?

**Comment by iskigow** [comment] 2022-10-05 01:58
I'm having 403 too but with other error message:

request:
```JSON
{
    "entity": "https://github.com",
    "is_debugging": false,
    "plugin": "browser-wakatime/2.0.1",
    "project": "CodeReview",
    "time": "1664933792",
    "type": "domain"
}
```

response:
`403 (Forbidden)`
```JSON
{
    "error": "You don't have the permission to access the requested resource. It is either read-protected or not readable by the server."
}
```

Searching about this error I found that maybe it is related to the **_csrf token_**.  One of the suggestion is add the `X-CSRFToken` header.  I try to add it using the csrftoken cookie info, but don't works too.

![image](https://user-images.githubusercontent.com/30843/193962599-06b2a029-5843-4812-973c-3b8f4555456c.png)
![image](https://user-images.githubusercontent.com/30843/193962817-288c7246-12c8-4728-82f6-c4a41f185b3d.png)

**Comment by jvelezpo** [comment] 2023-03-15 21:14
Closing this, since this was solved on v3

**Closed by jvelezpo** 2023-03-15 21:14 UTC
Labels: question
