### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by retardsroo** [wakatime/chrome-wakatime#71] opened 2018-10-18 09:38 UTC
Hello I am unable to login into plugin. I just get redirected to dashboard. I tried to sign off wakatime and again in using the plugin but still it looks I am not logged in.
EDIT, okay I left it unattended and went for a smoke and now it logged in somehow so you can close this issue I guess
EDIT2: OK i looks like it keeps me loggin on and off on random...

**Comment by zhgabor** [comment] 2018-11-28 09:46
I can confirm the same behavior
![waka-bug](https://user-images.githubusercontent.com/12900744/49143229-47366a00-f303-11e8-8c19-258b7bed4b8b.png)

**Comment by tarnos12** [comment] 2018-12-06 09:53
Same happened to me today.  
Wakatime was down for a while, then I got an email with my goals information(exactly at 10:01 AM my time)  
So I can assume that wakatime downtime was caused by this(It was sending emails to everyone :?)  

Can't log in, even tho I am logged in on wakatime, so extension isn't working.

**Comment by michaelwittig** [comment] 2019-02-08 15:22
Same here. I solved it for now but logging out via https://wakatime.com/logout
and then I clicked the Login button of the extension

**Comment by geekyouth** [comment] 2019-02-28 05:33
> Same here. I solved it for now but logging out via https://wakatime.com/logout
> and then I clicked the Login button of the extension

thank you so much , success!!!

**Comment by alanhamlett** [comment] 2023-01-10 15:40
Duplicate of #55

**Comment by jvelezpo** [comment] 2023-02-24 14:33
Closing this, since there is a new version of the extension that uses api key instead of a cookie

**Closed** 2023-03-16 06:59 UTC
