### ISSUE TITLE
Custom recognition of projects from URL

### ISSUE THREAD

**Issue by MiniGod** [wakatime/chrome-wakatime#54] opened 2017-05-28 01:18 UTC
Instead of only sending heartbeats for `<<LAST_PROJECT>>`, it would be great if I could get the project from the URL. For instance, on GitHub, you can grab the project name from the 2nd segment of the URL path.

This would be helpful if your team does a lot of pull requests and want to log time to the project of the PR you're reviewing rather than what you were working on last.

Would be helpful to have it for Bitbucket and Bitbucket server as well (custom domains).

**Comment by alanhamlett** [comment] 2017-05-28 18:12
Duplicate of #47

**Closed** 2017-05-28 18:12 UTC
